DATA:
  NUM_WORKERS: 4
  SCORE_CLASSES: 3
  TRAIN:
    ROOT_DIR: "data/ycb_data/training_data_yuzhepipline"
  VAL:
    ROOT_DIR: "data/ycb_data/training_data_yuzhepipline"
  TEST:
    ROOT_DIR: "data/ycb_data/eval_data_nonoise"
MODEL:
  TYPE: "PN2_CLS"
  PN2:
    RADIUS: (0.02, 0.08, 0.32)
    NUM_INPUT: 25600
    NUM_CENTROIDS: (5120, 1024, 256)
    NUM_NEIGHBOURS: (64, 64, 64)
    SA_CHANNELS: ((128, 128, 256), (256, 256, 512), (512, 512, 1024))
    FP_CHANNELS: ((1024, 1024), (512, 512), (256, 256, 256))
    NUM_FP_NEIGHBOURS: (3, 3, 3)
    LABEL_SMOOTHING: 0.0
    NEG_WEIGHT: 0.5
    SEG_CHANNELS: (512, 256, 256, 128)
SOLVER:
  BASE_LR: 0.001
SCHEDULER:
  MAX_EPOCH: 205
  TYPE: "StepLR"
  StepLR:
    step_size: 20
    gamma: 0.5
TRAIN:
  BATCH_SIZE: 2
  LOG_PERIOD: 5
  FILE_LOG_PERIOD: 100
  CHECKPOINT_PERIOD: 10
TEST:
  WEIGHT: ${PROJECT_HOME}/trained_models/curvature_model.pth
  BATCH_SIZE: 1
  LOG_PERIOD: 5
  FILE_LOG_PERIOD: 100